#pragma once

// Generated by LGFXScreenBuilder (formatVersion 1). Do not edit by hand.
// Include <LovyanGFX.hpp> (or M5GFX) and <LGFXScreenBuilder.h> before this header.

namespace Sfm {

enum class Profile : uint8_t { Auto = 0, Core, Stick, AtomS3 };

namespace Scene {
  struct Boot {
    static constexpr lgfxsb::SceneId id = 0;
    const char* logoText = "SFM";
    const char* titleText = "FACTORY MONITOR";
    const char* subTitleText = "SMART FACTORY";
    const char* versionText = "v1.0.0 / CORE";
  };
  struct Dashboard {
    static constexpr lgfxsb::SceneId id = 1;
    const char* titleText = "FACTORY MONITOR";
    const char* clockText = "14:32";
    const char* tempLabel = "TEMP";
    const char* tempValue = "26.4C";
    const char* humLabel = "HUM";
    const char* humValue = "48%";
    const char* co2Label = "CO2";
    const char* co2Value = "780";
    const char* lineTitle = "LINE STATUS";
    const char* line1Name = "LINE-1";
    const char* line1Value = "RUN";
    const char* line2Name = "LINE-2";
    const char* line2Value = "IDLE";
    const char* alertTitle = "ALERTS";
    const char* alertCount = "2";
    const char* alertState = "WARN";
    const char* btnA = "MENU";
    const char* btnB = "DETAIL";
    const char* btnC = "ACK";
  };
  struct AlertList {
    static constexpr lgfxsb::SceneId id = 2;
    const char* titleText = "ALERTS";
    const char* countText = "3";
    const char* level1 = "!";
    const char* message1 = "MOTOR OVERLOAD";
    const char* meta1 = "14:28  CRITICAL";
    const char* level2 = "!";
    const char* message2 = "TEMP HIGH";
    const char* meta2 = "14:12  WARNING";
    const char* level3 = "i";
    const char* message3 = "FILTER MAINTENANCE";
    const char* meta3 = "09:40  INFO";
    const char* btnA = "BACK";
    const char* btnB = "OPEN";
    const char* btnC = "ACK";
  };
  struct SensorDetail {
    static constexpr lgfxsb::SceneId id = 3;
    const char* titleText = "SENSOR DETAIL";
    const char* sensorNameText = "TEMP-01";
    const char* valueLabel = "TEMPERATURE";
    const char* valueText = "26.4";
    const char* unitText = "C";
    const char* stateText = "NORMAL";
    const char* minLabel = "MIN";
    const char* minValue = "23.1";
    const char* avgLabel = "AVG";
    const char* avgValue = "25.8";
    const char* maxLabel = "MAX";
    const char* maxValue = "29.4";
    const char* thresholdTitle = "THRESHOLD";
    const char* highLabel = "HI";
    const char* highValue = "30.0";
    const char* lowLabel = "LO";
    const char* lowValue = "18.0";
    const char* trendTitle = "TREND";
    const char* btnA = "BACK";
    const char* btnB = "NEXT";
    const char* btnC = "ACK";
  };
  struct EquipmentStatus {
    static constexpr lgfxsb::SceneId id = 4;
    const char* titleText = "EQUIPMENT";
    const char* summaryText = "4 RUN / 1 ERR";
    const char* headName = "UNIT";
    const char* headState = "STATE";
    const char* headLoad = "LOAD";
    const char* headCode = "CODE";
    const char* name1 = "LINE-1";
    const char* state1 = "RUN";
    const char* load1 = "92%";
    const char* code1 = "--";
    const char* name2 = "LINE-2";
    const char* state2 = "IDLE";
    const char* load2 = "0%";
    const char* code2 = "--";
    const char* name3 = "LINE-3";
    const char* state3 = "ERROR";
    const char* load3 = "--";
    const char* code3 = "E104";
    const char* name4 = "PUMP-A";
    const char* state4 = "RUN";
    const char* load4 = "68%";
    const char* code4 = "--";
    const char* name5 = "FAN-B";
    const char* state5 = "OFF";
    const char* load5 = "0%";
    const char* code5 = "--";
    const char* btnA = "BACK";
    const char* btnB = "DETAIL";
    const char* btnC = "RESET";
  };
  struct NetworkStatus {
    static constexpr lgfxsb::SceneId id = 5;
    const char* titleText = "NETWORK";
    const char* summaryText = "ONLINE";
    const char* wifiTitle = "WI-FI";
    const char* wifiStatusLabel = "STATE";
    const char* wifiStatusValue = "CONNECTED";
    const char* ssidLabel = "SSID";
    const char* ssidValue = "Factory_AP_01";
    const char* mqttTitle = "MQTT";
    const char* mqttStatusLabel = "STATE";
    const char* mqttStatusValue = "CONNECTED";
    const char* brokerLabel = "BROKER";
    const char* brokerValue = "10.0.0.12";
    const char* ipTitle = "DEVICE NETWORK";
    const char* ipLabel = "IP";
    const char* ipValue = "192.168.10.42";
    const char* rssiLabel = "RSSI";
    const char* rssiValue = "-58dBm";
    const char* deviceLabel = "DEVICE";
    const char* deviceValue = "M5-FAC-001";
    const char* btnA = "BACK";
    const char* btnB = "SCAN";
    const char* btnC = "RESET";
  };
  struct Settings {
    static constexpr lgfxsb::SceneId id = 6;
    const char* titleText = "SETTINGS";
    const char* summaryText = "DEVICE";
    const char* brightnessLabel = "BRIGHTNESS";
    const char* brightnessValue = "80%";
    const char* brightnessNote = "LCD LEVEL";
    const char* alertSoundLabel = "ALERT SOUND";
    const char* alertSoundValue = "ON";
    const char* alertSoundNote = "BUZZER";
    const char* sendIntervalLabel = "SEND INTERVAL";
    const char* sendIntervalValue = "5 sec";
    const char* sendIntervalNote = "MQTT";
    const char* deviceIdLabel = "DEVICE ID";
    const char* deviceIdValue = "M5-FAC-001";
    const char* deviceIdNote = "FACTORY NODE";
    const char* btnA = "BACK";
    const char* btnB = "EDIT";
    const char* btnC = "SAVE";
  };
}

namespace detail {

static const lgfxsb::PartDesc kParts[] = {
  {"frame", lgfxsb::PartType::Rect, nullptr, -1},  // 0 Boot.frame
  {"logoBox", lgfxsb::PartType::Rect, nullptr, -1},  // 1 Boot.logoBox
  {"logoText", lgfxsb::PartType::Text, "SFM", -1},  // 2 Boot.logoText
  {"titleText", lgfxsb::PartType::Text, "FACTORY MONITOR", -1},  // 3 Boot.titleText
  {"subTitleText", lgfxsb::PartType::Text, "SMART FACTORY", -1},  // 4 Boot.subTitleText
  {"progressGuide", lgfxsb::PartType::Rect, nullptr, -1},  // 5 Boot.progressGuide
  {"statusArea", lgfxsb::PartType::Rect, nullptr, -1},  // 6 Boot.statusArea
  {"versionText", lgfxsb::PartType::Text, "v1.0.0 / CORE", -1},  // 7 Boot.versionText
  {"titleText", lgfxsb::PartType::Text, "FACTORY MONITOR", -1},  // 8 Dashboard.titleText
  {"clockText", lgfxsb::PartType::Text, "14:32", -1},  // 9 Dashboard.clockText
  {"headerLine", lgfxsb::PartType::Line, nullptr, -1},  // 10 Dashboard.headerLine
  {"tempCard", lgfxsb::PartType::Rect, nullptr, -1},  // 11 Dashboard.tempCard
  {"tempLabel", lgfxsb::PartType::Text, "TEMP", -1},  // 12 Dashboard.tempLabel
  {"tempValue", lgfxsb::PartType::Text, "26.4C", -1},  // 13 Dashboard.tempValue
  {"humCard", lgfxsb::PartType::Rect, nullptr, -1},  // 14 Dashboard.humCard
  {"humLabel", lgfxsb::PartType::Text, "HUM", -1},  // 15 Dashboard.humLabel
  {"humValue", lgfxsb::PartType::Text, "48%", -1},  // 16 Dashboard.humValue
  {"co2Card", lgfxsb::PartType::Rect, nullptr, -1},  // 17 Dashboard.co2Card
  {"co2Label", lgfxsb::PartType::Text, "CO2", -1},  // 18 Dashboard.co2Label
  {"co2Value", lgfxsb::PartType::Text, "780", -1},  // 19 Dashboard.co2Value
  {"linePanel", lgfxsb::PartType::Rect, nullptr, -1},  // 20 Dashboard.linePanel
  {"lineTitle", lgfxsb::PartType::Text, "LINE STATUS", -1},  // 21 Dashboard.lineTitle
  {"line1Name", lgfxsb::PartType::Text, "LINE-1", -1},  // 22 Dashboard.line1Name
  {"line1Value", lgfxsb::PartType::Text, "RUN", -1},  // 23 Dashboard.line1Value
  {"line2Name", lgfxsb::PartType::Text, "LINE-2", -1},  // 24 Dashboard.line2Name
  {"line2Value", lgfxsb::PartType::Text, "IDLE", -1},  // 25 Dashboard.line2Value
  {"alertPanel", lgfxsb::PartType::Rect, nullptr, -1},  // 26 Dashboard.alertPanel
  {"alertTitle", lgfxsb::PartType::Text, "ALERTS", -1},  // 27 Dashboard.alertTitle
  {"alertCount", lgfxsb::PartType::Text, "2", -1},  // 28 Dashboard.alertCount
  {"alertState", lgfxsb::PartType::Text, "WARN", -1},  // 29 Dashboard.alertState
  {"footerLine", lgfxsb::PartType::Line, nullptr, -1},  // 30 Dashboard.footerLine
  {"btnA", lgfxsb::PartType::Text, "MENU", -1},  // 31 Dashboard.btnA
  {"btnB", lgfxsb::PartType::Text, "DETAIL", -1},  // 32 Dashboard.btnB
  {"btnC", lgfxsb::PartType::Text, "ACK", -1},  // 33 Dashboard.btnC
  {"titleText", lgfxsb::PartType::Text, "ALERTS", -1},  // 34 AlertList.titleText
  {"countText", lgfxsb::PartType::Text, "3", -1},  // 35 AlertList.countText
  {"headerLine", lgfxsb::PartType::Line, nullptr, -1},  // 36 AlertList.headerLine
  {"row1", lgfxsb::PartType::Rect, nullptr, -1},  // 37 AlertList.row1
  {"level1", lgfxsb::PartType::Text, "!", -1},  // 38 AlertList.level1
  {"message1", lgfxsb::PartType::Text, "MOTOR OVERLOAD", -1},  // 39 AlertList.message1
  {"meta1", lgfxsb::PartType::Text, "14:28  CRITICAL", -1},  // 40 AlertList.meta1
  {"row2", lgfxsb::PartType::Rect, nullptr, -1},  // 41 AlertList.row2
  {"level2", lgfxsb::PartType::Text, "!", -1},  // 42 AlertList.level2
  {"message2", lgfxsb::PartType::Text, "TEMP HIGH", -1},  // 43 AlertList.message2
  {"meta2", lgfxsb::PartType::Text, "14:12  WARNING", -1},  // 44 AlertList.meta2
  {"row3", lgfxsb::PartType::Rect, nullptr, -1},  // 45 AlertList.row3
  {"level3", lgfxsb::PartType::Text, "i", -1},  // 46 AlertList.level3
  {"message3", lgfxsb::PartType::Text, "FILTER MAINTENANCE", -1},  // 47 AlertList.message3
  {"meta3", lgfxsb::PartType::Text, "09:40  INFO", -1},  // 48 AlertList.meta3
  {"footerLine", lgfxsb::PartType::Line, nullptr, -1},  // 49 AlertList.footerLine
  {"btnA", lgfxsb::PartType::Text, "BACK", -1},  // 50 AlertList.btnA
  {"btnB", lgfxsb::PartType::Text, "OPEN", -1},  // 51 AlertList.btnB
  {"btnC", lgfxsb::PartType::Text, "ACK", -1},  // 52 AlertList.btnC
  {"titleText", lgfxsb::PartType::Text, "SENSOR DETAIL", -1},  // 53 SensorDetail.titleText
  {"sensorNameText", lgfxsb::PartType::Text, "TEMP-01", -1},  // 54 SensorDetail.sensorNameText
  {"headerLine", lgfxsb::PartType::Line, nullptr, -1},  // 55 SensorDetail.headerLine
  {"mainCard", lgfxsb::PartType::Rect, nullptr, -1},  // 56 SensorDetail.mainCard
  {"valueLabel", lgfxsb::PartType::Text, "TEMPERATURE", -1},  // 57 SensorDetail.valueLabel
  {"valueText", lgfxsb::PartType::Text, "26.4", -1},  // 58 SensorDetail.valueText
  {"unitText", lgfxsb::PartType::Text, "C", -1},  // 59 SensorDetail.unitText
  {"stateText", lgfxsb::PartType::Text, "NORMAL", -1},  // 60 SensorDetail.stateText
  {"minCard", lgfxsb::PartType::Rect, nullptr, -1},  // 61 SensorDetail.minCard
  {"minLabel", lgfxsb::PartType::Text, "MIN", -1},  // 62 SensorDetail.minLabel
  {"minValue", lgfxsb::PartType::Text, "23.1", -1},  // 63 SensorDetail.minValue
  {"avgCard", lgfxsb::PartType::Rect, nullptr, -1},  // 64 SensorDetail.avgCard
  {"avgLabel", lgfxsb::PartType::Text, "AVG", -1},  // 65 SensorDetail.avgLabel
  {"avgValue", lgfxsb::PartType::Text, "25.8", -1},  // 66 SensorDetail.avgValue
  {"maxCard", lgfxsb::PartType::Rect, nullptr, -1},  // 67 SensorDetail.maxCard
  {"maxLabel", lgfxsb::PartType::Text, "MAX", -1},  // 68 SensorDetail.maxLabel
  {"maxValue", lgfxsb::PartType::Text, "29.4", -1},  // 69 SensorDetail.maxValue
  {"thresholdPanel", lgfxsb::PartType::Rect, nullptr, -1},  // 70 SensorDetail.thresholdPanel
  {"thresholdTitle", lgfxsb::PartType::Text, "THRESHOLD", -1},  // 71 SensorDetail.thresholdTitle
  {"highLabel", lgfxsb::PartType::Text, "HI", -1},  // 72 SensorDetail.highLabel
  {"highValue", lgfxsb::PartType::Text, "30.0", -1},  // 73 SensorDetail.highValue
  {"lowLabel", lgfxsb::PartType::Text, "LO", -1},  // 74 SensorDetail.lowLabel
  {"lowValue", lgfxsb::PartType::Text, "18.0", -1},  // 75 SensorDetail.lowValue
  {"trendPanel", lgfxsb::PartType::Rect, nullptr, -1},  // 76 SensorDetail.trendPanel
  {"trendTitle", lgfxsb::PartType::Text, "TREND", -1},  // 77 SensorDetail.trendTitle
  {"trendGrid1", lgfxsb::PartType::Line, nullptr, -1},  // 78 SensorDetail.trendGrid1
  {"trendGrid2", lgfxsb::PartType::Line, nullptr, -1},  // 79 SensorDetail.trendGrid2
  {"trendGrid3", lgfxsb::PartType::Line, nullptr, -1},  // 80 SensorDetail.trendGrid3
  {"trendAxisL", lgfxsb::PartType::Line, nullptr, -1},  // 81 SensorDetail.trendAxisL
  {"trendAxisR", lgfxsb::PartType::Line, nullptr, -1},  // 82 SensorDetail.trendAxisR
  {"footerLine", lgfxsb::PartType::Line, nullptr, -1},  // 83 SensorDetail.footerLine
  {"btnA", lgfxsb::PartType::Text, "BACK", -1},  // 84 SensorDetail.btnA
  {"btnB", lgfxsb::PartType::Text, "NEXT", -1},  // 85 SensorDetail.btnB
  {"btnC", lgfxsb::PartType::Text, "ACK", -1},  // 86 SensorDetail.btnC
  {"titleText", lgfxsb::PartType::Text, "EQUIPMENT", -1},  // 87 EquipmentStatus.titleText
  {"summaryText", lgfxsb::PartType::Text, "4 RUN / 1 ERR", -1},  // 88 EquipmentStatus.summaryText
  {"headerLine", lgfxsb::PartType::Line, nullptr, -1},  // 89 EquipmentStatus.headerLine
  {"tableHeader", lgfxsb::PartType::Rect, nullptr, -1},  // 90 EquipmentStatus.tableHeader
  {"headName", lgfxsb::PartType::Text, "UNIT", -1},  // 91 EquipmentStatus.headName
  {"headState", lgfxsb::PartType::Text, "STATE", -1},  // 92 EquipmentStatus.headState
  {"headLoad", lgfxsb::PartType::Text, "LOAD", -1},  // 93 EquipmentStatus.headLoad
  {"headCode", lgfxsb::PartType::Text, "CODE", -1},  // 94 EquipmentStatus.headCode
  {"row1", lgfxsb::PartType::Rect, nullptr, -1},  // 95 EquipmentStatus.row1
  {"name1", lgfxsb::PartType::Text, "LINE-1", -1},  // 96 EquipmentStatus.name1
  {"state1", lgfxsb::PartType::Text, "RUN", -1},  // 97 EquipmentStatus.state1
  {"load1", lgfxsb::PartType::Text, "92%", -1},  // 98 EquipmentStatus.load1
  {"code1", lgfxsb::PartType::Text, "--", -1},  // 99 EquipmentStatus.code1
  {"row2", lgfxsb::PartType::Rect, nullptr, -1},  // 100 EquipmentStatus.row2
  {"name2", lgfxsb::PartType::Text, "LINE-2", -1},  // 101 EquipmentStatus.name2
  {"state2", lgfxsb::PartType::Text, "IDLE", -1},  // 102 EquipmentStatus.state2
  {"load2", lgfxsb::PartType::Text, "0%", -1},  // 103 EquipmentStatus.load2
  {"code2", lgfxsb::PartType::Text, "--", -1},  // 104 EquipmentStatus.code2
  {"row3", lgfxsb::PartType::Rect, nullptr, -1},  // 105 EquipmentStatus.row3
  {"name3", lgfxsb::PartType::Text, "LINE-3", -1},  // 106 EquipmentStatus.name3
  {"state3", lgfxsb::PartType::Text, "ERROR", -1},  // 107 EquipmentStatus.state3
  {"load3", lgfxsb::PartType::Text, "--", -1},  // 108 EquipmentStatus.load3
  {"code3", lgfxsb::PartType::Text, "E104", -1},  // 109 EquipmentStatus.code3
  {"row4", lgfxsb::PartType::Rect, nullptr, -1},  // 110 EquipmentStatus.row4
  {"name4", lgfxsb::PartType::Text, "PUMP-A", -1},  // 111 EquipmentStatus.name4
  {"state4", lgfxsb::PartType::Text, "RUN", -1},  // 112 EquipmentStatus.state4
  {"load4", lgfxsb::PartType::Text, "68%", -1},  // 113 EquipmentStatus.load4
  {"code4", lgfxsb::PartType::Text, "--", -1},  // 114 EquipmentStatus.code4
  {"row5", lgfxsb::PartType::Rect, nullptr, -1},  // 115 EquipmentStatus.row5
  {"name5", lgfxsb::PartType::Text, "FAN-B", -1},  // 116 EquipmentStatus.name5
  {"state5", lgfxsb::PartType::Text, "OFF", -1},  // 117 EquipmentStatus.state5
  {"load5", lgfxsb::PartType::Text, "0%", -1},  // 118 EquipmentStatus.load5
  {"code5", lgfxsb::PartType::Text, "--", -1},  // 119 EquipmentStatus.code5
  {"footerLine", lgfxsb::PartType::Line, nullptr, -1},  // 120 EquipmentStatus.footerLine
  {"btnA", lgfxsb::PartType::Text, "BACK", -1},  // 121 EquipmentStatus.btnA
  {"btnB", lgfxsb::PartType::Text, "DETAIL", -1},  // 122 EquipmentStatus.btnB
  {"btnC", lgfxsb::PartType::Text, "RESET", -1},  // 123 EquipmentStatus.btnC
  {"titleText", lgfxsb::PartType::Text, "NETWORK", -1},  // 124 NetworkStatus.titleText
  {"summaryText", lgfxsb::PartType::Text, "ONLINE", -1},  // 125 NetworkStatus.summaryText
  {"headerLine", lgfxsb::PartType::Line, nullptr, -1},  // 126 NetworkStatus.headerLine
  {"wifiPanel", lgfxsb::PartType::Rect, nullptr, -1},  // 127 NetworkStatus.wifiPanel
  {"wifiTitle", lgfxsb::PartType::Text, "WI-FI", -1},  // 128 NetworkStatus.wifiTitle
  {"wifiStatusLabel", lgfxsb::PartType::Text, "STATE", -1},  // 129 NetworkStatus.wifiStatusLabel
  {"wifiStatusValue", lgfxsb::PartType::Text, "CONNECTED", -1},  // 130 NetworkStatus.wifiStatusValue
  {"ssidLabel", lgfxsb::PartType::Text, "SSID", -1},  // 131 NetworkStatus.ssidLabel
  {"ssidValue", lgfxsb::PartType::Text, "Factory_AP_01", -1},  // 132 NetworkStatus.ssidValue
  {"mqttPanel", lgfxsb::PartType::Rect, nullptr, -1},  // 133 NetworkStatus.mqttPanel
  {"mqttTitle", lgfxsb::PartType::Text, "MQTT", -1},  // 134 NetworkStatus.mqttTitle
  {"mqttStatusLabel", lgfxsb::PartType::Text, "STATE", -1},  // 135 NetworkStatus.mqttStatusLabel
  {"mqttStatusValue", lgfxsb::PartType::Text, "CONNECTED", -1},  // 136 NetworkStatus.mqttStatusValue
  {"brokerLabel", lgfxsb::PartType::Text, "BROKER", -1},  // 137 NetworkStatus.brokerLabel
  {"brokerValue", lgfxsb::PartType::Text, "10.0.0.12", -1},  // 138 NetworkStatus.brokerValue
  {"ipPanel", lgfxsb::PartType::Rect, nullptr, -1},  // 139 NetworkStatus.ipPanel
  {"ipTitle", lgfxsb::PartType::Text, "DEVICE NETWORK", -1},  // 140 NetworkStatus.ipTitle
  {"ipLabel", lgfxsb::PartType::Text, "IP", -1},  // 141 NetworkStatus.ipLabel
  {"ipValue", lgfxsb::PartType::Text, "192.168.10.42", -1},  // 142 NetworkStatus.ipValue
  {"rssiLabel", lgfxsb::PartType::Text, "RSSI", -1},  // 143 NetworkStatus.rssiLabel
  {"rssiValue", lgfxsb::PartType::Text, "-58dBm", -1},  // 144 NetworkStatus.rssiValue
  {"devicePanel", lgfxsb::PartType::Rect, nullptr, -1},  // 145 NetworkStatus.devicePanel
  {"deviceLabel", lgfxsb::PartType::Text, "DEVICE", -1},  // 146 NetworkStatus.deviceLabel
  {"deviceValue", lgfxsb::PartType::Text, "M5-FAC-001", -1},  // 147 NetworkStatus.deviceValue
  {"footerLine", lgfxsb::PartType::Line, nullptr, -1},  // 148 NetworkStatus.footerLine
  {"btnA", lgfxsb::PartType::Text, "BACK", -1},  // 149 NetworkStatus.btnA
  {"btnB", lgfxsb::PartType::Text, "SCAN", -1},  // 150 NetworkStatus.btnB
  {"btnC", lgfxsb::PartType::Text, "RESET", -1},  // 151 NetworkStatus.btnC
  {"titleText", lgfxsb::PartType::Text, "SETTINGS", -1},  // 152 Settings.titleText
  {"summaryText", lgfxsb::PartType::Text, "DEVICE", -1},  // 153 Settings.summaryText
  {"headerLine", lgfxsb::PartType::Line, nullptr, -1},  // 154 Settings.headerLine
  {"brightnessRow", lgfxsb::PartType::Rect, nullptr, -1},  // 155 Settings.brightnessRow
  {"brightnessLabel", lgfxsb::PartType::Text, "BRIGHTNESS", -1},  // 156 Settings.brightnessLabel
  {"brightnessValue", lgfxsb::PartType::Text, "80%", -1},  // 157 Settings.brightnessValue
  {"brightnessNote", lgfxsb::PartType::Text, "LCD LEVEL", -1},  // 158 Settings.brightnessNote
  {"alertSoundRow", lgfxsb::PartType::Rect, nullptr, -1},  // 159 Settings.alertSoundRow
  {"alertSoundLabel", lgfxsb::PartType::Text, "ALERT SOUND", -1},  // 160 Settings.alertSoundLabel
  {"alertSoundValue", lgfxsb::PartType::Text, "ON", -1},  // 161 Settings.alertSoundValue
  {"alertSoundNote", lgfxsb::PartType::Text, "BUZZER", -1},  // 162 Settings.alertSoundNote
  {"sendIntervalRow", lgfxsb::PartType::Rect, nullptr, -1},  // 163 Settings.sendIntervalRow
  {"sendIntervalLabel", lgfxsb::PartType::Text, "SEND INTERVAL", -1},  // 164 Settings.sendIntervalLabel
  {"sendIntervalValue", lgfxsb::PartType::Text, "5 sec", -1},  // 165 Settings.sendIntervalValue
  {"sendIntervalNote", lgfxsb::PartType::Text, "MQTT", -1},  // 166 Settings.sendIntervalNote
  {"deviceIdRow", lgfxsb::PartType::Rect, nullptr, -1},  // 167 Settings.deviceIdRow
  {"deviceIdLabel", lgfxsb::PartType::Text, "DEVICE ID", -1},  // 168 Settings.deviceIdLabel
  {"deviceIdValue", lgfxsb::PartType::Text, "M5-FAC-001", -1},  // 169 Settings.deviceIdValue
  {"deviceIdNote", lgfxsb::PartType::Text, "FACTORY NODE", -1},  // 170 Settings.deviceIdNote
  {"footerLine", lgfxsb::PartType::Line, nullptr, -1},  // 171 Settings.footerLine
  {"btnA", lgfxsb::PartType::Text, "BACK", -1},  // 172 Settings.btnA
  {"btnB", lgfxsb::PartType::Text, "EDIT", -1},  // 173 Settings.btnB
  {"btnC", lgfxsb::PartType::Text, "SAVE", -1},  // 174 Settings.btnC
};
static constexpr uint16_t kPartCount = 175;

static const lgfxsb::SceneDesc kScenes[] = {
  {0, "Boot", 0, 8},
  {1, "Dashboard", 8, 26},
  {2, "AlertList", 34, 19},
  {3, "SensorDetail", 53, 34},
  {4, "EquipmentStatus", 87, 37},
  {5, "NetworkStatus", 124, 28},
  {6, "Settings", 152, 23},
};

// {x, y, w, h, x2, y2, r, datum, size, color, fill, visible, font}
static const lgfxsb::PartLayout kLayouts[] = {
  // ---- Profile: Core 320x240 rot0 ----
  {58, 52, 204, 126, 0, 0, 10, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Boot.frame
  {114, 76, 92, 38, 0, 0, 6, 0, 0.0f, 0x101a1f, true, true, nullptr},  // Boot.logoBox
  {160, 95, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Orbitron_Light_24},  // Boot.logoText
  {160, 133, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu18},  // Boot.titleText
  {160, 155, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // Boot.subTitleText
  {98, 194, 124, 4, 0, 0, 2, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Boot.progressGuide
  {118, 204, 84, 14, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // Boot.statusArea
  {160, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x455a57, true, true, &lgfx::v1::fonts::Font0},  // Boot.versionText
  {10, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::ML, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // Dashboard.titleText
  {282, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // Dashboard.clockText
  {0, 30, 0, 0, 320, 30, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Dashboard.headerLine
  {10, 42, 95, 62, 0, 0, 6, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Dashboard.tempCard
  {57, 55, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.tempLabel
  {57, 80, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu18},  // Dashboard.tempValue
  {113, 42, 95, 62, 0, 0, 6, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Dashboard.humCard
  {160, 55, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.humLabel
  {160, 80, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu18},  // Dashboard.humValue
  {216, 42, 94, 62, 0, 0, 6, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Dashboard.co2Card
  {263, 55, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.co2Label
  {263, 80, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu18},  // Dashboard.co2Value
  {10, 116, 145, 66, 0, 0, 6, 0, 0.0f, 0x233532, false, true, nullptr},  // Dashboard.linePanel
  {82, 130, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.lineTitle
  {45, 151, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.line1Name
  {112, 151, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.line1Value
  {45, 167, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.line2Name
  {112, 167, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.line2Value
  {165, 116, 145, 66, 0, 0, 6, 0, 0.0f, 0x233532, false, true, nullptr},  // Dashboard.alertPanel
  {237, 130, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.alertTitle
  {205, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu24},  // Dashboard.alertCount
  {265, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // Dashboard.alertState
  {0, 210, 0, 0, 320, 210, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Dashboard.footerLine
  {54, 225, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.btnA
  {160, 225, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.btnB
  {266, 225, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.btnC
  {10, 17, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::ML, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu18},  // AlertList.titleText
  {286, 17, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu18},  // AlertList.countText
  {0, 34, 0, 0, 320, 34, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // AlertList.headerLine
  {10, 46, 300, 38, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // AlertList.row1
  {31, 65, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // AlertList.level1
  {166, 58, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // AlertList.message1
  {166, 73, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.meta1
  {10, 94, 300, 38, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // AlertList.row2
  {31, 113, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // AlertList.level2
  {166, 106, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // AlertList.message2
  {166, 121, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.meta2
  {10, 142, 300, 38, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // AlertList.row3
  {31, 161, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu12},  // AlertList.level3
  {166, 154, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // AlertList.message3
  {166, 169, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.meta3
  {0, 210, 0, 0, 320, 210, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // AlertList.footerLine
  {54, 225, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // AlertList.btnA
  {160, 225, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // AlertList.btnB
  {266, 225, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // AlertList.btnC
  {10, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::ML, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // SensorDetail.titleText
  {252, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // SensorDetail.sensorNameText
  {0, 30, 0, 0, 320, 30, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // SensorDetail.headerLine
  {10, 42, 140, 76, 0, 0, 6, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // SensorDetail.mainCard
  {80, 56, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // SensorDetail.valueLabel
  {80, 83, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu24},  // SensorDetail.valueText
  {126, 84, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu12},  // SensorDetail.unitText
  {80, 106, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // SensorDetail.stateText
  {160, 42, 46, 36, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.minCard
  {183, 53, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.minLabel
  {183, 68, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.minValue
  {215, 42, 46, 36, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.avgCard
  {238, 53, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.avgLabel
  {238, 68, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.avgValue
  {270, 42, 40, 36, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.maxCard
  {290, 53, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.maxLabel
  {290, 68, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.maxValue
  {160, 86, 150, 32, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.thresholdPanel
  {235, 96, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.thresholdTitle
  {190, 110, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.highLabel
  {218, 110, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.highValue
  {258, 110, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.lowLabel
  {286, 110, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.lowValue
  {10, 130, 300, 68, 0, 0, 6, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.trendPanel
  {42, 142, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.trendTitle
  {20, 152, 0, 0, 300, 152, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // SensorDetail.trendGrid1
  {20, 168, 0, 0, 300, 168, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // SensorDetail.trendGrid2
  {20, 184, 0, 0, 300, 184, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // SensorDetail.trendGrid3
  {20, 144, 0, 0, 20, 190, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // SensorDetail.trendAxisL
  {300, 144, 0, 0, 300, 190, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // SensorDetail.trendAxisR
  {0, 210, 0, 0, 320, 210, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // SensorDetail.footerLine
  {54, 225, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // SensorDetail.btnA
  {160, 225, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // SensorDetail.btnB
  {266, 225, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // SensorDetail.btnC
  {10, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::ML, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // EquipmentStatus.titleText
  {262, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.summaryText
  {0, 30, 0, 0, 320, 30, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // EquipmentStatus.headerLine
  {10, 40, 300, 18, 0, 0, 4, 0, 0.0f, 0x101a1f, true, true, nullptr},  // EquipmentStatus.tableHeader
  {48, 49, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headName
  {132, 49, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headState
  {210, 49, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headLoad
  {278, 49, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headCode
  {10, 64, 300, 26, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row1
  {48, 77, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.name1
  {132, 77, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.state1
  {210, 77, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.load1
  {278, 77, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code1
  {10, 96, 300, 26, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row2
  {48, 109, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.name2
  {132, 109, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.state2
  {210, 109, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.load2
  {278, 109, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code2
  {10, 128, 300, 26, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // EquipmentStatus.row3
  {48, 141, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.name3
  {132, 141, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.state3
  {210, 141, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.load3
  {278, 141, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code3
  {10, 160, 300, 26, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row4
  {48, 173, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.name4
  {132, 173, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.state4
  {210, 173, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.load4
  {278, 173, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code4
  {10, 192, 300, 14, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row5
  {48, 199, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.name5
  {132, 199, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.state5
  {210, 199, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load5
  {278, 199, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code5
  {0, 214, 0, 0, 320, 214, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // EquipmentStatus.footerLine
  {54, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.btnA
  {160, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.btnB
  {266, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.btnC
  {10, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::ML, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // NetworkStatus.titleText
  {268, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // NetworkStatus.summaryText
  {0, 30, 0, 0, 320, 30, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // NetworkStatus.headerLine
  {10, 42, 145, 70, 0, 0, 6, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // NetworkStatus.wifiPanel
  {82, 56, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.wifiTitle
  {48, 78, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.wifiStatusLabel
  {112, 78, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.wifiStatusValue
  {48, 96, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.ssidLabel
  {112, 96, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.ssidValue
  {165, 42, 145, 70, 0, 0, 6, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // NetworkStatus.mqttPanel
  {237, 56, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.mqttTitle
  {202, 78, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.mqttStatusLabel
  {266, 78, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.mqttStatusValue
  {202, 96, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.brokerLabel
  {266, 96, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.brokerValue
  {10, 124, 300, 54, 0, 0, 6, 0, 0.0f, 0x233532, false, true, nullptr},  // NetworkStatus.ipPanel
  {160, 138, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.ipTitle
  {54, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.ipLabel
  {128, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.ipValue
  {218, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.rssiLabel
  {278, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.rssiValue
  {10, 186, 300, 18, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // NetworkStatus.devicePanel
  {62, 195, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.deviceLabel
  {190, 195, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.deviceValue
  {0, 214, 0, 0, 320, 214, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // NetworkStatus.footerLine
  {54, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.btnA
  {160, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.btnB
  {266, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.btnC
  {10, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::ML, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // Settings.titleText
  {268, 15, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // Settings.summaryText
  {0, 30, 0, 0, 320, 30, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Settings.headerLine
  {10, 44, 300, 34, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Settings.brightnessRow
  {82, 61, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.brightnessLabel
  {235, 61, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // Settings.brightnessValue
  {235, 72, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.brightnessNote
  {10, 88, 300, 34, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // Settings.alertSoundRow
  {82, 105, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.alertSoundLabel
  {235, 105, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // Settings.alertSoundValue
  {235, 116, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.alertSoundNote
  {10, 132, 300, 34, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // Settings.sendIntervalRow
  {82, 149, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.sendIntervalLabel
  {235, 149, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu12},  // Settings.sendIntervalValue
  {235, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.sendIntervalNote
  {10, 176, 300, 28, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // Settings.deviceIdRow
  {82, 190, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.deviceIdLabel
  {235, 190, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.deviceIdValue
  {235, 199, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.deviceIdNote
  {0, 214, 0, 0, 320, 214, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Settings.footerLine
  {54, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.btnA
  {160, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.btnB
  {266, 228, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.btnC
  // ---- Profile: Stick 135x240 rot0 ----
  {13, 52, 109, 126, 0, 0, 9, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Boot.frame
  {33, 78, 69, 34, 0, 0, 6, 0, 0.0f, 0x101a1f, true, true, nullptr},  // Boot.logoBox
  {67, 95, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 0.8f, 0xffffff, true, true, &lgfx::v1::fonts::Orbitron_Light_24},  // Boot.logoText
  {67, 132, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // Boot.titleText
  {67, 150, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // Boot.subTitleText
  {27, 196, 81, 4, 0, 0, 2, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Boot.progressGuide
  {39, 207, 57, 14, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // Boot.statusArea
  {67, 229, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x455a57, true, true, &lgfx::v1::fonts::Font0},  // Boot.versionText
  {67, 12, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // Dashboard.titleText
  {67, 12, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::DejaVu12},  // Dashboard.clockText
  {8, 26, 0, 0, 127, 26, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Dashboard.headerLine
  {10, 36, 115, 38, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Dashboard.tempCard
  {34, 55, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.tempLabel
  {88, 55, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.tempValue
  {10, 82, 115, 38, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Dashboard.humCard
  {34, 101, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.humLabel
  {88, 101, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.humValue
  {10, 82, 115, 38, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, false, nullptr},  // Dashboard.co2Card
  {34, 101, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::DejaVu9},  // Dashboard.co2Label
  {88, 101, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::DejaVu9},  // Dashboard.co2Value
  {10, 128, 115, 38, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // Dashboard.linePanel
  {34, 147, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.lineTitle
  {34, 147, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::DejaVu9},  // Dashboard.line1Name
  {88, 147, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // Dashboard.line1Value
  {34, 147, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::DejaVu9},  // Dashboard.line2Name
  {88, 147, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::DejaVu9},  // Dashboard.line2Value
  {10, 174, 115, 30, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // Dashboard.alertPanel
  {40, 189, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.alertTitle
  {96, 189, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.alertCount
  {96, 189, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.alertState
  {8, 214, 0, 0, 127, 214, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Dashboard.footerLine
  {23, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.btnA
  {67, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.btnB
  {111, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.btnC
  {67, 14, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // AlertList.titleText
  {116, 14, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // AlertList.countText
  {8, 28, 0, 0, 127, 28, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // AlertList.headerLine
  {8, 42, 119, 42, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // AlertList.row1
  {19, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // AlertList.level1
  {73, 56, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // AlertList.message1
  {73, 73, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.meta1
  {8, 94, 119, 42, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // AlertList.row2
  {19, 115, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // AlertList.level2
  {73, 108, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // AlertList.message2
  {73, 125, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.meta2
  {8, 146, 119, 42, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // AlertList.row3
  {19, 167, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.level3
  {73, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // AlertList.message3
  {73, 177, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.meta3
  {8, 214, 0, 0, 127, 214, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // AlertList.footerLine
  {23, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.btnA
  {67, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.btnB
  {111, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.btnC
  {67, 12, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // SensorDetail.titleText
  {67, 25, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.sensorNameText
  {8, 34, 0, 0, 127, 34, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // SensorDetail.headerLine
  {10, 44, 115, 58, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // SensorDetail.mainCard
  {67, 56, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.valueLabel
  {67, 78, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // SensorDetail.valueText
  {104, 78, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.unitText
  {67, 94, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.stateText
  {10, 112, 35, 30, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.minCard
  {27, 122, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.minLabel
  {27, 136, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.minValue
  {50, 112, 35, 30, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.avgCard
  {67, 122, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.avgLabel
  {67, 136, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.avgValue
  {90, 112, 35, 30, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.maxCard
  {107, 122, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.maxLabel
  {107, 136, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.maxValue
  {10, 152, 115, 30, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.thresholdPanel
  {67, 162, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.thresholdTitle
  {30, 176, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.highLabel
  {54, 176, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.highValue
  {82, 176, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.lowLabel
  {106, 176, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.lowValue
  {10, 190, 115, 16, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.trendPanel
  {67, 198, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.trendTitle
  {14, 195, 0, 0, 121, 195, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendGrid1
  {14, 198, 0, 0, 121, 198, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendGrid2
  {14, 201, 0, 0, 121, 201, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendGrid3
  {14, 194, 0, 0, 14, 202, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendAxisL
  {121, 194, 0, 0, 121, 202, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendAxisR
  {8, 214, 0, 0, 127, 214, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // SensorDetail.footerLine
  {23, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.btnA
  {67, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.btnB
  {111, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.btnC
  {67, 12, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // EquipmentStatus.titleText
  {67, 25, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.summaryText
  {8, 34, 0, 0, 127, 34, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // EquipmentStatus.headerLine
  {10, 42, 115, 14, 0, 0, 4, 0, 0.0f, 0x101a1f, true, true, nullptr},  // EquipmentStatus.tableHeader
  {34, 49, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headName
  {82, 49, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headState
  {112, 49, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headLoad
  {112, 49, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headCode
  {10, 64, 115, 24, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row1
  {34, 76, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.name1
  {82, 76, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.state1
  {112, 76, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load1
  {112, 76, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code1
  {10, 94, 115, 24, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row2
  {34, 106, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.name2
  {82, 106, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.state2
  {112, 106, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load2
  {112, 106, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code2
  {10, 124, 115, 24, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // EquipmentStatus.row3
  {34, 136, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.name3
  {82, 136, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.state3
  {112, 136, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load3
  {112, 136, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code3
  {10, 154, 115, 24, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row4
  {34, 166, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.name4
  {82, 166, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // EquipmentStatus.state4
  {112, 166, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load4
  {112, 166, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code4
  {10, 184, 115, 20, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row5
  {34, 194, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.name5
  {82, 194, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.state5
  {112, 194, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load5
  {112, 194, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code5
  {8, 214, 0, 0, 127, 214, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // EquipmentStatus.footerLine
  {23, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.btnA
  {67, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.btnB
  {111, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.btnC
  {67, 12, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // NetworkStatus.titleText
  {67, 25, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.summaryText
  {8, 34, 0, 0, 127, 34, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // NetworkStatus.headerLine
  {10, 44, 115, 38, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // NetworkStatus.wifiPanel
  {34, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.wifiTitle
  {34, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.wifiStatusLabel
  {88, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.wifiStatusValue
  {34, 73, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.ssidLabel
  {88, 73, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.ssidValue
  {10, 92, 115, 38, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // NetworkStatus.mqttPanel
  {34, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.mqttTitle
  {34, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.mqttStatusLabel
  {88, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::DejaVu9},  // NetworkStatus.mqttStatusValue
  {34, 121, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.brokerLabel
  {88, 121, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.brokerValue
  {10, 140, 115, 38, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // NetworkStatus.ipPanel
  {67, 150, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.ipTitle
  {34, 166, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.ipLabel
  {88, 166, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.ipValue
  {34, 166, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.rssiLabel
  {88, 166, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.rssiValue
  {10, 188, 115, 18, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // NetworkStatus.devicePanel
  {38, 197, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.deviceLabel
  {86, 197, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.deviceValue
  {8, 214, 0, 0, 127, 214, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // NetworkStatus.footerLine
  {23, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.btnA
  {67, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.btnB
  {111, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.btnC
  {67, 12, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu12},  // Settings.titleText
  {67, 25, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.summaryText
  {8, 34, 0, 0, 127, 34, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Settings.headerLine
  {10, 46, 115, 34, 0, 0, 5, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Settings.brightnessRow
  {42, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.brightnessLabel
  {96, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.brightnessValue
  {96, 74, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.brightnessNote
  {10, 90, 115, 34, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // Settings.alertSoundRow
  {42, 107, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.alertSoundLabel
  {96, 107, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.alertSoundValue
  {96, 118, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.alertSoundNote
  {10, 134, 115, 34, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // Settings.sendIntervalRow
  {42, 151, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.sendIntervalLabel
  {96, 151, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.sendIntervalValue
  {96, 162, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.sendIntervalNote
  {10, 178, 115, 28, 0, 0, 5, 0, 0.0f, 0x233532, false, true, nullptr},  // Settings.deviceIdRow
  {42, 192, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Settings.deviceIdLabel
  {96, 192, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.deviceIdValue
  {96, 202, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.deviceIdNote
  {8, 214, 0, 0, 127, 214, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Settings.footerLine
  {23, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // Settings.btnA
  {67, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // Settings.btnB
  {111, 226, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // Settings.btnC
  // ---- Profile: AtomS3 128x128 rot0 ----
  {10, 10, 108, 92, 0, 0, 8, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Boot.frame
  {33, 24, 62, 28, 0, 0, 5, 0, 0.0f, 0x101a1f, true, true, nullptr},  // Boot.logoBox
  {64, 38, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 0.65f, 0xffffff, true, true, &lgfx::v1::fonts::Orbitron_Light_24},  // Boot.logoText
  {64, 66, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::DejaVu9},  // Boot.titleText
  {64, 80, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Boot.subTitleText
  {28, 108, 72, 4, 0, 0, 2, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Boot.progressGuide
  {118, 204, 84, 14, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // Boot.statusArea
  {64, 122, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x455a57, true, true, &lgfx::v1::fonts::Font0},  // Boot.versionText
  {64, 9, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.titleText
  {64, 9, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.clockText
  {12, 18, 0, 0, 116, 18, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Dashboard.headerLine
  {12, 26, 104, 27, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Dashboard.tempCard
  {36, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.tempLabel
  {84, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.tempValue
  {12, 26, 104, 27, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, false, nullptr},  // Dashboard.humCard
  {36, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.humLabel
  {84, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.humValue
  {12, 26, 104, 27, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, false, nullptr},  // Dashboard.co2Card
  {36, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.co2Label
  {84, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.co2Value
  {12, 61, 104, 27, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // Dashboard.linePanel
  {36, 75, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.lineTitle
  {36, 75, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.line1Name
  {84, 75, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.line1Value
  {36, 75, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.line2Name
  {84, 75, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.line2Value
  {12, 96, 104, 22, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // Dashboard.alertPanel
  {44, 107, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.alertTitle
  {84, 107, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Dashboard.alertCount
  {84, 107, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.alertState
  {12, 121, 0, 0, 116, 121, 0, 0, 0.0f, 0x233532, true, false, nullptr},  // Dashboard.footerLine
  {24, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.btnA
  {64, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.btnB
  {104, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Dashboard.btnC
  {64, 9, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // AlertList.titleText
  {112, 9, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // AlertList.countText
  {12, 18, 0, 0, 116, 18, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // AlertList.headerLine
  {12, 26, 104, 28, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // AlertList.row1
  {25, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // AlertList.level1
  {72, 36, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // AlertList.message1
  {72, 47, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.meta1
  {12, 62, 104, 28, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // AlertList.row2
  {25, 76, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // AlertList.level2
  {72, 72, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // AlertList.message2
  {72, 83, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // AlertList.meta2
  {12, 96, 104, 22, 0, 0, 4, 0, 0.0f, 0x233532, false, false, nullptr},  // AlertList.row3
  {25, 107, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // AlertList.level3
  {72, 103, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // AlertList.message3
  {72, 114, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // AlertList.meta3
  {12, 121, 0, 0, 116, 121, 0, 0, 0.0f, 0x233532, true, false, nullptr},  // AlertList.footerLine
  {24, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // AlertList.btnA
  {64, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // AlertList.btnB
  {104, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // AlertList.btnC
  {64, 9, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.titleText
  {64, 20, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.sensorNameText
  {12, 28, 0, 0, 116, 28, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // SensorDetail.headerLine
  {12, 36, 104, 36, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // SensorDetail.mainCard
  {38, 54, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.valueLabel
  {84, 54, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.valueText
  {108, 54, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.unitText
  {64, 65, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.stateText
  {12, 80, 31, 22, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.minCard
  {27, 88, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.minLabel
  {27, 98, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.minValue
  {48, 80, 32, 22, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.avgCard
  {64, 88, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.avgLabel
  {64, 98, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.avgValue
  {85, 80, 31, 22, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.maxCard
  {100, 88, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.maxLabel
  {100, 98, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.maxValue
  {12, 108, 104, 12, 0, 0, 3, 0, 0.0f, 0x233532, false, true, nullptr},  // SensorDetail.thresholdPanel
  {64, 114, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // SensorDetail.thresholdTitle
  {24, 114, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.highLabel
  {48, 114, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.highValue
  {78, 114, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.lowLabel
  {102, 114, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.lowValue
  {12, 108, 104, 12, 0, 0, 3, 0, 0.0f, 0x233532, false, false, nullptr},  // SensorDetail.trendPanel
  {64, 114, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.trendTitle
  {12, 112, 0, 0, 116, 112, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendGrid1
  {12, 115, 0, 0, 116, 115, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendGrid2
  {12, 118, 0, 0, 116, 118, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendGrid3
  {12, 110, 0, 0, 12, 118, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendAxisL
  {116, 110, 0, 0, 116, 118, 0, 0, 0.0f, 0x1e2a30, true, false, nullptr},  // SensorDetail.trendAxisR
  {12, 122, 0, 0, 116, 122, 0, 0, 0.0f, 0x233532, true, false, nullptr},  // SensorDetail.footerLine
  {24, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.btnA
  {64, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.btnB
  {104, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // SensorDetail.btnC
  {64, 9, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.titleText
  {64, 20, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.summaryText
  {12, 28, 0, 0, 116, 28, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // EquipmentStatus.headerLine
  {12, 36, 104, 12, 0, 0, 3, 0, 0.0f, 0x101a1f, true, true, nullptr},  // EquipmentStatus.tableHeader
  {36, 42, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headName
  {84, 42, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headState
  {84, 42, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headLoad
  {84, 42, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.headCode
  {12, 54, 104, 18, 0, 0, 3, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row1
  {36, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.name1
  {84, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.state1
  {104, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load1
  {104, 63, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code1
  {12, 78, 104, 18, 0, 0, 3, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // EquipmentStatus.row2
  {36, 87, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.name2
  {84, 87, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.state2
  {104, 87, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load2
  {104, 87, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code2
  {12, 102, 104, 18, 0, 0, 3, 0, 0.0f, 0x233532, false, true, nullptr},  // EquipmentStatus.row3
  {36, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.name3
  {84, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // EquipmentStatus.state3
  {104, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load3
  {104, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code3
  {12, 102, 104, 18, 0, 0, 3, 0, 0.0f, 0x233532, false, false, nullptr},  // EquipmentStatus.row4
  {36, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.name4
  {84, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.state4
  {104, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load4
  {104, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code4
  {12, 102, 104, 18, 0, 0, 3, 0, 0.0f, 0x233532, false, false, nullptr},  // EquipmentStatus.row5
  {36, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.name5
  {84, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.state5
  {104, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.load5
  {104, 111, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.code5
  {12, 122, 0, 0, 116, 122, 0, 0, 0.0f, 0x233532, true, false, nullptr},  // EquipmentStatus.footerLine
  {24, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.btnA
  {64, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.btnB
  {104, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // EquipmentStatus.btnC
  {64, 9, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.titleText
  {64, 20, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.summaryText
  {12, 28, 0, 0, 116, 28, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // NetworkStatus.headerLine
  {12, 36, 104, 20, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // NetworkStatus.wifiPanel
  {36, 46, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.wifiTitle
  {36, 46, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.wifiStatusLabel
  {84, 46, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.wifiStatusValue
  {36, 46, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.ssidLabel
  {84, 46, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.ssidValue
  {12, 64, 104, 20, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // NetworkStatus.mqttPanel
  {36, 74, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.mqttTitle
  {36, 74, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.mqttStatusLabel
  {84, 74, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.mqttStatusValue
  {36, 74, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.brokerLabel
  {84, 74, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.brokerValue
  {12, 92, 104, 26, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // NetworkStatus.ipPanel
  {64, 101, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.ipTitle
  {36, 105, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.ipLabel
  {84, 105, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // NetworkStatus.ipValue
  {36, 114, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.rssiLabel
  {84, 114, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.rssiValue
  {12, 92, 104, 26, 0, 0, 4, 0, 0.0f, 0x233532, false, false, nullptr},  // NetworkStatus.devicePanel
  {36, 105, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.deviceLabel
  {84, 105, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.deviceValue
  {12, 122, 0, 0, 116, 122, 0, 0, 0.0f, 0x233532, true, false, nullptr},  // NetworkStatus.footerLine
  {24, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.btnA
  {64, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.btnB
  {104, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // NetworkStatus.btnC
  {64, 9, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // Settings.titleText
  {64, 20, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.summaryText
  {12, 28, 0, 0, 116, 28, 0, 0, 0.0f, 0x233532, true, true, nullptr},  // Settings.headerLine
  {12, 36, 104, 18, 0, 0, 4, 0, 0.0f, 0x2a8f8a, false, true, nullptr},  // Settings.brightnessRow
  {40, 45, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // Settings.brightnessLabel
  {86, 45, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.brightnessValue
  {86, 52, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.brightnessNote
  {12, 61, 104, 18, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // Settings.alertSoundRow
  {40, 70, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // Settings.alertSoundLabel
  {86, 70, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.alertSoundValue
  {86, 77, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.alertSoundNote
  {12, 86, 104, 18, 0, 0, 4, 0, 0.0f, 0x233532, false, true, nullptr},  // Settings.sendIntervalRow
  {40, 95, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::Font0},  // Settings.sendIntervalLabel
  {86, 95, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, true, &lgfx::v1::fonts::Font0},  // Settings.sendIntervalValue
  {86, 102, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.sendIntervalNote
  {12, 110, 104, 10, 0, 0, 3, 0, 0.0f, 0x233532, false, false, nullptr},  // Settings.deviceIdRow
  {40, 115, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0xffffff, true, false, &lgfx::v1::fonts::Font0},  // Settings.deviceIdLabel
  {86, 115, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x9ce5ac, true, false, &lgfx::v1::fonts::Font0},  // Settings.deviceIdValue
  {86, 115, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.deviceIdNote
  {12, 122, 0, 0, 116, 122, 0, 0, 0.0f, 0x233532, true, false, nullptr},  // Settings.footerLine
  {24, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.btnA
  {64, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.btnB
  {104, 124, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.0f, 0x6f8f89, true, false, &lgfx::v1::fonts::Font0},  // Settings.btnC
};

static const lgfxsb::ProfileDesc kProfiles[] = {
  {320, 240, 0},
  {135, 240, 0},
  {128, 128, 0},
};

struct ProfileInfo {
  const char* name;
  uint8_t index;
  int16_t w, h;
  uint8_t rotation;
};

struct SceneInfo {
  const char* name;
  lgfxsb::SceneId id;
  uint16_t index;
};

static constexpr ProfileInfo kProfileInfo[] = {
  {"Core", 0, 320, 240, 0},
  {"Stick", 1, 135, 240, 0},
  {"AtomS3", 2, 128, 128, 0},
};
static constexpr uint8_t kProfileInfoCount = 3;

static constexpr SceneInfo kSceneInfo[] = {
  {"Boot", Scene::Boot::id, 0},
  {"Dashboard", Scene::Dashboard::id, 1},
  {"AlertList", Scene::AlertList::id, 2},
  {"SensorDetail", Scene::SensorDetail::id, 3},
  {"EquipmentStatus", Scene::EquipmentStatus::id, 4},
  {"NetworkStatus", Scene::NetworkStatus::id, 5},
  {"Settings", Scene::Settings::id, 6},
};
static constexpr uint16_t kSceneInfoCount = 7;


} // namespace detail

static const lgfxsb::Project project = {
  detail::kProfiles, 3,
  detail::kScenes, 7,
  detail::kParts, detail::kPartCount,
  detail::kLayouts,
  /*background*/ 0x000000,
  nullptr, 0,
};

#if defined(LGFXVIRTUALCANVAS_H)
using Canvas = LGFXVirtualCanvas;
#else
using Canvas = lgfx::LGFXBase;
#endif

class Screen : public lgfxsb::RendererT<Canvas> {
  using Base = lgfxsb::RendererT<Canvas>;
  void (*_ov_Boot)(Canvas&, const Scene::Boot&) = nullptr;
  static void _ovt_Boot(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Boot&)>(fnp))(g, *static_cast<const Scene::Boot*>(s)); }
  void (*_ov_Dashboard)(Canvas&, const Scene::Dashboard&) = nullptr;
  static void _ovt_Dashboard(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Dashboard&)>(fnp))(g, *static_cast<const Scene::Dashboard*>(s)); }
  void (*_ov_AlertList)(Canvas&, const Scene::AlertList&) = nullptr;
  static void _ovt_AlertList(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::AlertList&)>(fnp))(g, *static_cast<const Scene::AlertList*>(s)); }
  void (*_ov_SensorDetail)(Canvas&, const Scene::SensorDetail&) = nullptr;
  static void _ovt_SensorDetail(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::SensorDetail&)>(fnp))(g, *static_cast<const Scene::SensorDetail*>(s)); }
  void (*_ov_EquipmentStatus)(Canvas&, const Scene::EquipmentStatus&) = nullptr;
  static void _ovt_EquipmentStatus(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::EquipmentStatus&)>(fnp))(g, *static_cast<const Scene::EquipmentStatus*>(s)); }
  void (*_ov_NetworkStatus)(Canvas&, const Scene::NetworkStatus&) = nullptr;
  static void _ovt_NetworkStatus(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::NetworkStatus&)>(fnp))(g, *static_cast<const Scene::NetworkStatus*>(s)); }
  void (*_ov_Settings)(Canvas&, const Scene::Settings&) = nullptr;
  static void _ovt_Settings(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Settings&)>(fnp))(g, *static_cast<const Scene::Settings*>(s)); }
 public:
  explicit Screen(lgfx::LGFX_Device& gfx) : Base(gfx, project) {}
  void setProfile(Profile p) { _profile = static_cast<uint8_t>(p); }
  void show(lgfxsb::SceneId id) { renderScene(id, nullptr, 0); }
  void show(const Scene::Boot& s) {
    lgfxsb::Value v[8];
    v[2] = lgfxsb::Value::text(s.logoText);
    v[3] = lgfxsb::Value::text(s.titleText);
    v[4] = lgfxsb::Value::text(s.subTitleText);
    v[7] = lgfxsb::Value::text(s.versionText);
    renderScene(Scene::Boot::id, v, 8, _ov_Boot ? &_ovt_Boot : nullptr, &s, &_ov_Boot);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Boot&)) { _ov_Boot = fn; }
  void show(const Scene::Dashboard& s) {
    lgfxsb::Value v[26];
    v[0] = lgfxsb::Value::text(s.titleText);
    v[1] = lgfxsb::Value::text(s.clockText);
    v[4] = lgfxsb::Value::text(s.tempLabel);
    v[5] = lgfxsb::Value::text(s.tempValue);
    v[7] = lgfxsb::Value::text(s.humLabel);
    v[8] = lgfxsb::Value::text(s.humValue);
    v[10] = lgfxsb::Value::text(s.co2Label);
    v[11] = lgfxsb::Value::text(s.co2Value);
    v[13] = lgfxsb::Value::text(s.lineTitle);
    v[14] = lgfxsb::Value::text(s.line1Name);
    v[15] = lgfxsb::Value::text(s.line1Value);
    v[16] = lgfxsb::Value::text(s.line2Name);
    v[17] = lgfxsb::Value::text(s.line2Value);
    v[19] = lgfxsb::Value::text(s.alertTitle);
    v[20] = lgfxsb::Value::text(s.alertCount);
    v[21] = lgfxsb::Value::text(s.alertState);
    v[23] = lgfxsb::Value::text(s.btnA);
    v[24] = lgfxsb::Value::text(s.btnB);
    v[25] = lgfxsb::Value::text(s.btnC);
    renderScene(Scene::Dashboard::id, v, 26, _ov_Dashboard ? &_ovt_Dashboard : nullptr, &s, &_ov_Dashboard);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Dashboard&)) { _ov_Dashboard = fn; }
  void show(const Scene::AlertList& s) {
    lgfxsb::Value v[19];
    v[0] = lgfxsb::Value::text(s.titleText);
    v[1] = lgfxsb::Value::text(s.countText);
    v[4] = lgfxsb::Value::text(s.level1);
    v[5] = lgfxsb::Value::text(s.message1);
    v[6] = lgfxsb::Value::text(s.meta1);
    v[8] = lgfxsb::Value::text(s.level2);
    v[9] = lgfxsb::Value::text(s.message2);
    v[10] = lgfxsb::Value::text(s.meta2);
    v[12] = lgfxsb::Value::text(s.level3);
    v[13] = lgfxsb::Value::text(s.message3);
    v[14] = lgfxsb::Value::text(s.meta3);
    v[16] = lgfxsb::Value::text(s.btnA);
    v[17] = lgfxsb::Value::text(s.btnB);
    v[18] = lgfxsb::Value::text(s.btnC);
    renderScene(Scene::AlertList::id, v, 19, _ov_AlertList ? &_ovt_AlertList : nullptr, &s, &_ov_AlertList);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::AlertList&)) { _ov_AlertList = fn; }
  void show(const Scene::SensorDetail& s) {
    lgfxsb::Value v[34];
    v[0] = lgfxsb::Value::text(s.titleText);
    v[1] = lgfxsb::Value::text(s.sensorNameText);
    v[4] = lgfxsb::Value::text(s.valueLabel);
    v[5] = lgfxsb::Value::text(s.valueText);
    v[6] = lgfxsb::Value::text(s.unitText);
    v[7] = lgfxsb::Value::text(s.stateText);
    v[9] = lgfxsb::Value::text(s.minLabel);
    v[10] = lgfxsb::Value::text(s.minValue);
    v[12] = lgfxsb::Value::text(s.avgLabel);
    v[13] = lgfxsb::Value::text(s.avgValue);
    v[15] = lgfxsb::Value::text(s.maxLabel);
    v[16] = lgfxsb::Value::text(s.maxValue);
    v[18] = lgfxsb::Value::text(s.thresholdTitle);
    v[19] = lgfxsb::Value::text(s.highLabel);
    v[20] = lgfxsb::Value::text(s.highValue);
    v[21] = lgfxsb::Value::text(s.lowLabel);
    v[22] = lgfxsb::Value::text(s.lowValue);
    v[24] = lgfxsb::Value::text(s.trendTitle);
    v[31] = lgfxsb::Value::text(s.btnA);
    v[32] = lgfxsb::Value::text(s.btnB);
    v[33] = lgfxsb::Value::text(s.btnC);
    renderScene(Scene::SensorDetail::id, v, 34, _ov_SensorDetail ? &_ovt_SensorDetail : nullptr, &s, &_ov_SensorDetail);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::SensorDetail&)) { _ov_SensorDetail = fn; }
  void show(const Scene::EquipmentStatus& s) {
    lgfxsb::Value v[37];
    v[0] = lgfxsb::Value::text(s.titleText);
    v[1] = lgfxsb::Value::text(s.summaryText);
    v[4] = lgfxsb::Value::text(s.headName);
    v[5] = lgfxsb::Value::text(s.headState);
    v[6] = lgfxsb::Value::text(s.headLoad);
    v[7] = lgfxsb::Value::text(s.headCode);
    v[9] = lgfxsb::Value::text(s.name1);
    v[10] = lgfxsb::Value::text(s.state1);
    v[11] = lgfxsb::Value::text(s.load1);
    v[12] = lgfxsb::Value::text(s.code1);
    v[14] = lgfxsb::Value::text(s.name2);
    v[15] = lgfxsb::Value::text(s.state2);
    v[16] = lgfxsb::Value::text(s.load2);
    v[17] = lgfxsb::Value::text(s.code2);
    v[19] = lgfxsb::Value::text(s.name3);
    v[20] = lgfxsb::Value::text(s.state3);
    v[21] = lgfxsb::Value::text(s.load3);
    v[22] = lgfxsb::Value::text(s.code3);
    v[24] = lgfxsb::Value::text(s.name4);
    v[25] = lgfxsb::Value::text(s.state4);
    v[26] = lgfxsb::Value::text(s.load4);
    v[27] = lgfxsb::Value::text(s.code4);
    v[29] = lgfxsb::Value::text(s.name5);
    v[30] = lgfxsb::Value::text(s.state5);
    v[31] = lgfxsb::Value::text(s.load5);
    v[32] = lgfxsb::Value::text(s.code5);
    v[34] = lgfxsb::Value::text(s.btnA);
    v[35] = lgfxsb::Value::text(s.btnB);
    v[36] = lgfxsb::Value::text(s.btnC);
    renderScene(Scene::EquipmentStatus::id, v, 37, _ov_EquipmentStatus ? &_ovt_EquipmentStatus : nullptr, &s, &_ov_EquipmentStatus);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::EquipmentStatus&)) { _ov_EquipmentStatus = fn; }
  void show(const Scene::NetworkStatus& s) {
    lgfxsb::Value v[28];
    v[0] = lgfxsb::Value::text(s.titleText);
    v[1] = lgfxsb::Value::text(s.summaryText);
    v[4] = lgfxsb::Value::text(s.wifiTitle);
    v[5] = lgfxsb::Value::text(s.wifiStatusLabel);
    v[6] = lgfxsb::Value::text(s.wifiStatusValue);
    v[7] = lgfxsb::Value::text(s.ssidLabel);
    v[8] = lgfxsb::Value::text(s.ssidValue);
    v[10] = lgfxsb::Value::text(s.mqttTitle);
    v[11] = lgfxsb::Value::text(s.mqttStatusLabel);
    v[12] = lgfxsb::Value::text(s.mqttStatusValue);
    v[13] = lgfxsb::Value::text(s.brokerLabel);
    v[14] = lgfxsb::Value::text(s.brokerValue);
    v[16] = lgfxsb::Value::text(s.ipTitle);
    v[17] = lgfxsb::Value::text(s.ipLabel);
    v[18] = lgfxsb::Value::text(s.ipValue);
    v[19] = lgfxsb::Value::text(s.rssiLabel);
    v[20] = lgfxsb::Value::text(s.rssiValue);
    v[22] = lgfxsb::Value::text(s.deviceLabel);
    v[23] = lgfxsb::Value::text(s.deviceValue);
    v[25] = lgfxsb::Value::text(s.btnA);
    v[26] = lgfxsb::Value::text(s.btnB);
    v[27] = lgfxsb::Value::text(s.btnC);
    renderScene(Scene::NetworkStatus::id, v, 28, _ov_NetworkStatus ? &_ovt_NetworkStatus : nullptr, &s, &_ov_NetworkStatus);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::NetworkStatus&)) { _ov_NetworkStatus = fn; }
  void show(const Scene::Settings& s) {
    lgfxsb::Value v[23];
    v[0] = lgfxsb::Value::text(s.titleText);
    v[1] = lgfxsb::Value::text(s.summaryText);
    v[4] = lgfxsb::Value::text(s.brightnessLabel);
    v[5] = lgfxsb::Value::text(s.brightnessValue);
    v[6] = lgfxsb::Value::text(s.brightnessNote);
    v[8] = lgfxsb::Value::text(s.alertSoundLabel);
    v[9] = lgfxsb::Value::text(s.alertSoundValue);
    v[10] = lgfxsb::Value::text(s.alertSoundNote);
    v[12] = lgfxsb::Value::text(s.sendIntervalLabel);
    v[13] = lgfxsb::Value::text(s.sendIntervalValue);
    v[14] = lgfxsb::Value::text(s.sendIntervalNote);
    v[16] = lgfxsb::Value::text(s.deviceIdLabel);
    v[17] = lgfxsb::Value::text(s.deviceIdValue);
    v[18] = lgfxsb::Value::text(s.deviceIdNote);
    v[20] = lgfxsb::Value::text(s.btnA);
    v[21] = lgfxsb::Value::text(s.btnB);
    v[22] = lgfxsb::Value::text(s.btnC);
    renderScene(Scene::Settings::id, v, 23, _ov_Settings ? &_ovt_Settings : nullptr, &s, &_ov_Settings);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Settings&)) { _ov_Settings = fn; }
};

} // namespace Sfm
